name: "Meross Local Broker Addon"
description: "Enables LAN-ONLY broker, avoiding Meross Cloud usage."
slug: "meross_local_broker"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  2001/tcp: 2001
  2002/tcp: 2002
  10001/tcp: 10001
ports_description:
  2001/tcp: "MQTT Broker port"
  2002/tcp: "HTTP API port"
  10001/tcp: "Remote debugger port"
ingress: true
ingress_port: 8099
host_network: true
homeassistant: "1.0.0"
options:
  email: "meross_local@local"
  password: "Changeme!"
  debug_mode: False
  federate_with_meross: False
schema:
  email: "str"
  password: "str"
  debug_mode: "bool"
  federate_with_meross: "bool"
image: albertogeniola/{arch}-meross_homeassistant_broker
version: "0.0.1-alpha1"
